import type { Reel } from "@/types/reels"

export const mockReels: Reel[] = [
  {
    id: "1",
    userId: "1",
    user: {
      id: "1",
      name: "Alex Chen",
      username: "alex_chen",
      avatar: "/placeholder.svg?height=40&width=40",
      isVerified: true,
    },
    videoUrl: "/placeholder-video.mp4",
    thumbnailUrl: "/student-room.png",
    caption: "My dorm room setup for finals week! 📚✨ #DormLife #StudyVibes #CollegeLife",
    duration: 15,
    likes: 1247,
    comments: 89,
    shares: 23,
    views: 5420,
    isLiked: false,
    isFollowing: false,
    hashtags: ["DormLife", "StudyVibes", "CollegeLife"],
    music: {
      id: "1",
      name: "Chill Study Beats",
      artist: "Lo-Fi Collective",
      url: "/placeholder-audio.mp3",
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    userId: "2",
    user: {
      id: "2",
      name: "Sarah Johnson",
      username: "sarah_sells",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    videoUrl: "/placeholder-video.mp4",
    thumbnailUrl: "/textbook-collection.png",
    caption:
      "Selling my textbooks from last semester! All in great condition 📖 DM me for prices #TextbookSale #CollegeSavings",
    duration: 12,
    likes: 892,
    comments: 156,
    shares: 45,
    views: 3210,
    isLiked: true,
    isFollowing: true,
    hashtags: ["TextbookSale", "CollegeSavings"],
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    userId: "3",
    user: {
      id: "3",
      name: "Mike Rodriguez",
      username: "mike_eats",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    videoUrl: "/placeholder-video.mp4",
    thumbnailUrl: "/campus-food-review.png",
    caption: "Rating campus dining hall food so you don't have to 🍕 Part 3/10 #CampusFood #FoodReview #StudentLife",
    duration: 18,
    likes: 2156,
    comments: 234,
    shares: 67,
    views: 8930,
    isLiked: false,
    isFollowing: false,
    hashtags: ["CampusFood", "FoodReview", "StudentLife"],
    music: {
      id: "2",
      name: "Upbeat Vibes",
      artist: "Campus Sounds",
      url: "/placeholder-audio.mp3",
    },
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
]
