import type { SellerMetrics, SalesData, Order, ProductAnalytics, CustomerInquiry } from "@/types/seller"

export const mockSellerMetrics: SellerMetrics = {
  totalRevenue: 2847.5,
  totalOrders: 23,
  totalProducts: 12,
  totalViews: 1456,
  conversionRate: 1.58,
  averageOrderValue: 123.8,
  revenueGrowth: 15.3,
  orderGrowth: 8.7,
}

export const mockSalesData: SalesData[] = [
  { date: "2024-01-01", revenue: 245.0, orders: 2, views: 89 },
  { date: "2024-01-02", revenue: 189.5, orders: 1, views: 67 },
  { date: "2024-01-03", revenue: 356.75, orders: 3, views: 124 },
  { date: "2024-01-04", revenue: 298.25, orders: 2, views: 98 },
  { date: "2024-01-05", revenue: 445.0, orders: 4, views: 156 },
  { date: "2024-01-06", revenue: 167.8, orders: 1, views: 78 },
  { date: "2024-01-07", revenue: 523.9, orders: 5, views: 189 },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    productId: "1",
    productName: "MacBook Pro 13-inch",
    productImage: "/placeholder.svg?height=60&width=60",
    buyerId: "buyer1",
    buyerName: "Sarah Johnson",
    buyerAvatar: "/placeholder.svg?height=40&width=40",
    quantity: 1,
    price: 899.0,
    total: 899.0,
    status: "shipped",
    paymentStatus: "paid",
    shippingAddress: "123 Campus Dr, University City, CA 90210",
    orderDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-002",
    productId: "2",
    productName: "Chemistry Textbook",
    productImage: "/placeholder.svg?height=60&width=60",
    buyerId: "buyer2",
    buyerName: "Mike Chen",
    buyerAvatar: "/placeholder.svg?height=40&width=40",
    quantity: 2,
    price: 45.0,
    total: 90.0,
    status: "confirmed",
    paymentStatus: "paid",
    shippingAddress: "456 Dorm Ave, University City, CA 90210",
    orderDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-003",
    productId: "3",
    productName: "Desk Lamp",
    productImage: "/placeholder.svg?height=60&width=60",
    buyerId: "buyer3",
    buyerName: "Emma Davis",
    buyerAvatar: "/placeholder.svg?height=40&width=40",
    quantity: 1,
    price: 25.99,
    total: 25.99,
    status: "pending",
    paymentStatus: "pending",
    shippingAddress: "789 Student St, University City, CA 90210",
    orderDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockProductAnalytics: ProductAnalytics[] = [
  {
    id: "1",
    name: "MacBook Pro 13-inch",
    image: "/placeholder.svg?height=60&width=60",
    views: 234,
    likes: 45,
    inquiries: 12,
    orders: 1,
    revenue: 899.0,
    conversionRate: 0.43,
    status: "active",
  },
  {
    id: "2",
    name: "Chemistry Textbook",
    image: "/placeholder.svg?height=60&width=60",
    views: 156,
    likes: 23,
    inquiries: 8,
    orders: 2,
    revenue: 90.0,
    conversionRate: 1.28,
    status: "active",
  },
  {
    id: "3",
    name: "Desk Lamp",
    image: "/placeholder.svg?height=60&width=60",
    views: 89,
    likes: 12,
    inquiries: 3,
    orders: 0,
    revenue: 0,
    conversionRate: 0,
    status: "active",
  },
]

export const mockCustomerInquiries: CustomerInquiry[] = [
  {
    id: "INQ-001",
    productId: "1",
    productName: "MacBook Pro 13-inch",
    customerId: "customer1",
    customerName: "Alex Rodriguez",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    message: "Is this still available? What's the battery condition?",
    status: "new",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "INQ-002",
    productId: "2",
    productName: "Chemistry Textbook",
    customerId: "customer2",
    customerName: "Lisa Wang",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    message: "Does this include the solution manual?",
    status: "responded",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
